"""
Generate quality report from geocoding results parquet.

Usage:
    python -m src.report --input data/output/results.parquet --source-xlsx data/input/nura.xlsx
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

import click
import pyarrow.parquet as pq


@click.command()
@click.option("--input", "results_path", required=True, type=click.Path(exists=True, path_type=Path))
@click.option("--source-xlsx", "source_path", default=None, type=click.Path(path_type=Path))
@click.option("--output", "report_path", default=None, type=click.Path(path_type=Path))
def main(results_path: Path, source_path: Path | None, report_path: Path | None) -> None:
    if report_path is None:
        report_path = Path("reports") / (results_path.stem + "_quality.md")
    report_path.parent.mkdir(parents=True, exist_ok=True)

    table = pq.read_table(str(results_path))
    df = table.to_pydict()

    total = len(df["sicid"])
    conf_counts = Counter(df["confidence"])
    source_counts = Counter(df["source"])
    remapped_count = sum(1 for v in df["name_remapped"] if v)

    lines = [
        f"# Geocoding Quality Report: `{results_path.name}`",
        "",
        f"**Total records:** {total:,}",
        "",
        "## Confidence breakdown",
        "",
        "| Confidence | Count | % |",
        "|------------|-------|---|",
    ]
    for conf in ["high", "medium", "low", "miss"]:
        n = conf_counts.get(conf, 0)
        pct = n / total * 100 if total else 0
        lines.append(f"| {conf} | {n:,} | {pct:.1f}% |")

    lines += [
        "",
        "## Source breakdown",
        "",
        "| Source | Count |",
        "|--------|-------|",
    ]
    for src, n in source_counts.most_common():
        lines.append(f"| {src} | {n:,} |")

    lines += [
        "",
        f"## Name remapping (alias substitutions): {remapped_count:,} ({remapped_count/total*100:.1f}%)",
        "",
        "## Miss / low confidence — top streets",
        "",
    ]

    # Find top miss/low streets
    miss_streets: Counter = Counter()
    for i, conf in enumerate(df["confidence"]):
        if conf in {"miss", "low"}:
            street = df["street_used"][i] or df["original_street"][i] or "?"
            miss_streets[street] += 1

    lines += [
        "| Street | Count |",
        "|--------|-------|",
    ]
    for street, n in miss_streets.most_common(30):
        lines.append(f"| {street} | {n} |")

    lines += [
        "",
        "## Remapped names — top aliases used",
        "",
        "| Original | Remapped | Count |",
        "|----------|----------|-------|",
    ]
    remap_pairs: Counter = Counter()
    for i, remapped in enumerate(df["name_remapped"]):
        if remapped:
            orig = df["original_street"][i] or "?"
            used = df["street_used"][i] or "?"
            remap_pairs[(orig, used)] += 1
    for (orig, used), n in remap_pairs.most_common(20):
        lines.append(f"| {orig} | {used} | {n} |")

    lines += ["", "---", "*Generated by src/report.py*"]

    report_text = "\n".join(lines)
    with report_path.open("w", encoding="utf-8") as f:
        f.write(report_text)

    click.echo(f"Report written to {report_path}")
    click.echo(f"  high:   {conf_counts.get('high',0):,} ({conf_counts.get('high',0)/total*100:.1f}%)")
    click.echo(f"  medium: {conf_counts.get('medium',0):,}")
    click.echo(f"  low:    {conf_counts.get('low',0):,}")
    click.echo(f"  miss:   {conf_counts.get('miss',0):,}")


if __name__ == "__main__":
    main()
